app_homepage:
    path: /
    controller: App\Controller\QuestionController::homepage

app_question_show:
    path: /question/{question}
    controller: App\Controller\QuestionController::show

app_comment_vote:
    path: /comments/{id}/vote/{isDirectionUp}
    controller: App\Controller\CommentController:commentVote
    methods: [ POST ]
    requirements:
        id: '(?!0)[\d]{0,9}'
        isDirectionUp: '[0-1]'
